version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}
  nginx_tls: {}

services:
  postgres:
    build: ./docker/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=tinyauth
      - POSTGRES_PASSWORD=tinyauth
      - POSTGRES_DB=tinyauth

  flask:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile-dev
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=tinyauth
      - POSTGRES_PASSWORD=tinyauth
    volumes:
      - .:/app/src
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: ./docker/ui/Dockerfile-dev
    volumes:
      - ./admin/src:/src/src
      - ./admin/public:/src/public

  login-ui:
    build:
      context: .
      dockerfile: ./docker/login-ui/Dockerfile-dev
    volumes:
      - ./login-ui/src:/src/src
      - ./login-ui/public:/src/public

  nginx:
    build: ./docker/nginx
    volumes:
      - nginx_tls:/etc/nginx/external/
    ports:
      - "0.0.0.0:443:443"
