version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  nginx_tls: {}
  audit: {}

services:
  postgres:
    build: ./docker/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    environment:
    - POSTGRES_DB=tinyauth
    - POSTGRES_USER=tinyauth
    - POSTGRES_PASSWORD=tinyauth
    restart: always

  flask:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    volumes:
      - audit:/app/var/audit
    depends_on:
      - postgres
    environment:
    - POSTGRES_USER=tinyauth
    - POSTGRES_PASSWORD=tinyauth
    - AUDIT_LOG_FILENAME=/app/var/audit/audit.log
    restart: always

  nginx:
    build: ./docker/nginx
    volumes:
      - nginx_tls:/etc/nginx/external/
    depends_on:
      - flask
    ports:
      - "0.0.0.0:443:443"
    restart: always
